"""Creation table download_links corrigee

Revision ID: 6d2a429b174f
Revises: 1b903e151acd
Create Date: 2025-09-11 22:26:47.570796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d2a429b174f'
down_revision = '1b903e151acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('traitement_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=500), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=1000), nullable=False),
    sa.Column('matricule_requis', sa.String(length=20), nullable=False),
    sa.Column('tentatives_acces', sa.Integer(), nullable=True),
    sa.Column('max_tentatives', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_expiration', sa.DateTime(), nullable=False),
    sa.Column('date_premier_acces', sa.DateTime(), nullable=True),
    sa.Column('date_dernier_acces', sa.DateTime(), nullable=True),
    sa.Column('nombre_telechargements', sa.Integer(), nullable=True),
    sa.Column('adresse_ip_derniere', sa.String(length=45), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['traitement_id'], ['traitements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_links', schema=None) as batch_op:
        batch_op.create_index('idx_download_token', ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_links_token'), ['token'], unique=True)

    with op.batch_alter_table('download_links_old', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_download_token'))

    #op.drop_table('download_links_old')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_links_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('employe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('traitement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.Column('matricule_hash', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employees.id'], name=op.f('download_links_employe_id_fkey')),
    sa.ForeignKeyConstraint(['traitement_id'], ['traitements.id'], name=op.f('download_links_traitement_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('download_links_pkey')),
    sa.UniqueConstraint('token', name=op.f('download_links_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('download_links_old', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_download_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('idx_download_expires'), ['expires_at'], unique=False)

    with op.batch_alter_table('download_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_links_token'))
        batch_op.drop_index('idx_download_token')

    op.drop_table('download_links')
    # ### end Alembic commands ###
