"""Ajout matricule comme identifiant principal

Revision ID: dd63d10659f5
Revises: eed2272c83e6
Create Date: 2025-09-11 19:57:13.394935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd63d10659f5'
down_revision = 'eed2272c83e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.String(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('employees_email_key'), type_='unique')
        batch_op.create_index('idx_employee_matricule', ['matricule'], unique=False)
        batch_op.create_unique_constraint(None, ['matricule'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_employee_matricule')
        batch_op.create_unique_constraint(batch_op.f('employees_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('matricule')

    # ### end Alembic commands ###
