"""Migration initiale v1.2 avec encodage UTF-8

Revision ID: eed2272c83e6
Revises: 
Create Date: 2025-09-08 23:43:19.298580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed2272c83e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_employe', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_derniere_maj', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('source_creation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('idx_employee_email', ['email'], unique=False)

    op.create_table('traitements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_folder', sa.String(length=20), nullable=False),
    sa.Column('fichier_original', sa.String(length=500), nullable=True),
    sa.Column('taille_fichier', sa.BigInteger(), nullable=True),
    sa.Column('nombre_pages', sa.Integer(), nullable=True),
    sa.Column('nombre_employes_detectes', sa.Integer(), nullable=True),
    sa.Column('nombre_employes_traites', sa.Integer(), nullable=True),
    sa.Column('nombre_nouveaux_employes', sa.Integer(), nullable=True),
    sa.Column('duree_traitement_secondes', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('erreurs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp_folder')
    )
    with op.batch_alter_table('traitements', schema=None) as batch_op:
        batch_op.create_index('idx_traitement_timestamp', ['timestamp_folder'], unique=False)

    """
        op.create_table('download_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('traitement_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('filepath', sa.String(length=800), nullable=False),
    sa.Column('matricule_hash', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['traitement_id'], ['traitements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('download_links', schema=None) as batch_op:
        batch_op.create_index('idx_download_expires', ['expires_at'], unique=False)
        batch_op.create_index('idx_download_token', ['token'], unique=False)
    """


    op.create_table('traitement_employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traitement_id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('matricule_extrait', sa.String(length=20), nullable=True),
    sa.Column('periode_extraite', sa.String(length=10), nullable=True),
    sa.Column('nom_fichier_genere', sa.String(length=500), nullable=True),
    sa.Column('email_envoye', sa.Boolean(), nullable=True),
    sa.Column('date_email', sa.DateTime(), nullable=True),
    sa.Column('erreur_email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['traitement_id'], ['traitements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traitement_employes')
    with op.batch_alter_table('download_links', schema=None) as batch_op:
        batch_op.drop_index('idx_download_token')
        batch_op.drop_index('idx_download_expires')

    op.drop_table('download_links')
    with op.batch_alter_table('traitements', schema=None) as batch_op:
        batch_op.drop_index('idx_traitement_timestamp')

    op.drop_table('traitements')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_email')

    op.drop_table('employees')
    # ### end Alembic commands ###
